### ISSUE TITLE
[newrelic-php-daemon] daemonConfig error

### ISSUE THREAD

**Issue by kriks57** [eMAGTechLabs/helm-charts#23]
Hi,

I tried to apply some daemonConfig entries in the values file.
ex:
```
daemonConfig:
  logfile: /dev/stdout
  app_timeout: "2m"
```

The generated newrelic.cfg file misses new lines, all is put on the same line : 

```
/ # cat /etc/newrelic/newrelic.cfg 
app_timeout=2m logfile=/dev/stdout
```

Did I miss something ?

**Comment by beniamin** [comment]
Sorry for late response. Just made a fix for that issue. Please check version 0.3.1
