### ISSUE TITLE
Support for tag override via values.yaml

### ISSUE THREAD

**Issue by krezovic** [eMAGTechLabs/helm-charts#8]
Hi,

It would be nice if tags could be overriden via values.yaml. Most helm charts support this approach, and it can be easier to swap versions for different cluster by maintaining different values.yaml (i.e. update on staging, but keep older for production).

**Comment by beniamin** [comment]
Good idea, I will take care of it.

**Comment by beniamin** [comment]
Can you give some examples? IMO if different environments(like staging, production) will have different releases and different labels because the release name is one of the labels.

**Comment by beniamin** [comment]
I just pushed the 0.1.7 version and added a new value `image.tag` that can be used to set a custom docker image tag to be used.
