### ISSUE TITLE
Support for LoadBalancerIP and LoadBalancerSourceRanges

### ISSUE THREAD

**Issue by krezovic** [eMAGTechLabs/helm-charts#9]
Hi,

It would be nice to be able to specify loadBalancerIP and loadBalancerSourceRanges properties of the service via values.yaml so haproxy could be deployed as a real load balancer.

**Comment by beniamin** [comment]
Sure thing. I will add support for loadBalancer in values.yaml.
If you want, feel free to send a PR and I will merge it.

**Comment by beniamin** [comment]
I added support for both `loadBalancerIP` and `loadBalancerSourceRanges`. Please upgrade to version 0.1.6
